data:
#    name: 'synthetic_shapes'
    dataset: 'SyntheticDataset_gaussian'
    primitives: 'all'
    truncate: {draw_ellipses: 0.3, draw_stripes: 0.2, gaussian_noise: 0.1}
    cache_in_memory: true
    suffix: 'v6'
    add_augmentation_to_test_set: false  # set to true to evaluate with noise
    gaussian_label:
        enable: false
        params:
            GaussianBlur: {sigma: 0.2}
    preprocessing: ## didn't do this
        blur_size: 21
        resize: [120, 160]
    augmentation:
        photometric:
            enable: true ## for class to recognize
            enable_train: true
            enable_val: false
            primitives: [
                'random_brightness', 'random_contrast', 'additive_speckle_noise',
                'additive_gaussian_noise', 'additive_shade', 'motion_blur' ]
            params:
                random_brightness: {max_abs_change: 75}
                random_contrast: {strength_range: [0.3, 1.8]}
                additive_gaussian_noise: {stddev_range: [0, 15]}
                additive_speckle_noise: {prob_range: [0, 0.0035]}
                additive_shade:
                    transparency_range: [-0.5, 0.8]
                    kernel_size_range: [50, 100]
                motion_blur: {max_kernel_size: 7} # origin 7
        homographic:
            enable: true
            enable_train: true
            enable_val: false
            params:
                translation: true
                rotation: true
                scaling: true
                perspective: true
                scaling_amplitude: 0.2
                perspective_amplitude_x: 0.2
                perspective_amplitude_y: 0.2
                patch_ratio: 0.8
                max_angle: 1.57  # 3.14
                allow_artifacts: true
                translation_overflow: 0.05
            valid_border_margin: 2
    warped_pair:
        enable: false # false when training only on detector
        params:
            translation: true
            rotation: true
            scaling: true
            perspective: true
            scaling_amplitude: 0.2
            perspective_amplitude_x: 0.2
            perspective_amplitude_y: 0.2
            patch_ratio: 0.85
            max_angle: 1.57
            allow_artifacts: true # true
        valid_border_margin: 3
        
front_end_model: 'Val_model_heatmap'  # 'Train_model_frontend'
model:
    name: 'SuperPointNet_gauss2' # SuperPointNet_heatmap
    params: {
    }

    # learning_rate: 0.0001 # 0.0001
    detection_threshold: 0.015 # 0.015

    batch_size: 1
    eval_batch_size: 1
    # output parameters
    learning_rate: 0.001
    detection_threshold: 0.015 # 0.001
    nms: 4
    top_k: 1000
    nn_thresh: 1.0 # 0.7
    homography_adaptation:
        num: 0
    subpixel: 
        enable: true
        patch_size: 5
    rand_noise:
        enable: false
        sigma: 0.2

    pretrained: 'logs/magicpoint_synth_t2/checkpoints/superPointNet_100000_checkpoint.pth.tar'

eval_iter: 1000
